#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'BevaBaseKit_Example' do
  pod 'BevaBaseKit', :path => '../'

  target 'BevaBaseKit_Tests' do
    inherit! :search_paths

    
  end
end
